// src/components/loader.tsx
import React, { FC, ReactElement } from 'react';
import { css, keyframes } from '@emotion/react';

// ==========================================
// Type
// ==========================================

// ==========================================
// Style
// ==========================================

const load8 = keyframes`
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
`;

const LoaderWrap = css`
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
`;

const loader = css`
  border-radius: 50%;
  width: 10em;
  height: 10em;

  margin: 0 auto 10px;
  font-size: 4px;
  position: relative;
  border-top: 0.6em solid rgba(255, 255, 255, 0.2);
  border-right: 0.6em solid rgba(255, 255, 255, 0.2);
  border-bottom: 0.6em solid rgba(255, 255, 255, 0.2);
  border-left: 0.6em solid #fff;
  transform: translateZ(0);
  animation: ${load8} 1.1s infinite linear;

  &::before {
    border-radius: 50%;
    width: 10em;
    height: 10em;
  }
`;

const LoaderText = css`
  font-size: 12px;
  color: #fff;
  letter-spacing: 0.3em;
  text-align: center;
  margin-right: -0.4em;
`;

// ==========================================
// View
// ==========================================

const Loader: FC = (): ReactElement => {
  return (
    <div css={LoaderWrap}>
      <div css={loader} />
      <p css={LoaderText}>Loading</p>
    </div>
  );
};

export default Loader;

// components/atoms/Loader.vue
<template lang="pug">
  .loader
</template>

<script>
export default {
  name: 'Loader'
};
</script>

<style lang="scss" scoped>
.loader {
  width: 100%;
  height: 100%;
  margin: 0 auto;
  position: relative;
  box-sizing: border-box;
  z-index: 0;

  &::before,
  &::after {
    opacity: 0;
    box-sizing: border-box;
    content: '\0020';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border-radius: 100px;
    border: 5px solid #fff;
    box-shadow: 0 0 50px #fff, inset 0 0 50px #fff;
  }

  &::before {
    z-index: 2;
    animation: loader 2s infinite;
  }

  &::after {
    z-index: 1;
    animation: loader 2s infinite 1s;
  }
}
</style>
